name: build-huawei-mate-9-kernel-kernelsu
on:
  workflow_dispatch:
  schedule:
      # Run once a week on Sunday at midnight. See http://crontab.guru
      - cron: '0 21 * * *'
  push:
    branches:
      - bick
  pull_request:
      branches:
      - bick
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_MAXSIZE: "2G"
      CCACHE_HARDLINK: "true"
      KERNEL_CMDLINE: "ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- O=out"
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        fetch-depth: 100

    - name: Set up ccache
      uses: hendrikmuhs/ccache-action@v1.2

    - name: Install dependencies
      run: |
        sudo apt-get update -y 
        sudo apt install binutils make python2 libssl-dev flex unzip libssl-dev ca-certificates xz-utils mkbootimg cpio device-tree-compiler git git-lfs bc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev adb fastboot -y
        git clone https://github.com/Coconutat/ToolChains.git --dept=1 -b linaro_gcc_4.9
    
    - name: get-time
      id: get_time
      run: |
        echo "TIME=$(TZ=UTC-8 date +%m%d%H%M )" >> $GITHUB_OUTPUT

    - name: build-kernel
      run: |
       rm -rf KernelSU
       rm -rf drivers/kernelsu
       curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main
       export PATH=$(pwd)/ToolChains/bin/:$PATH
       export ARCH=arm64
       export SUBARCH=arm64
       make ARCH=arm64  O=out -j$(nproc --all)
       cp out/arch/arm64/boot/Image.gz tools/kernel
       tools/pack_kernerimage_cmd.sh
    - name: upload-fruits
      uses: actions/upload-artifact@v3
      with:
        name: kernel.img
        path: kernel.img
